package com.shailesh.blc;

public class Patient {
    private static int idCounter=1;
   private int id;
   private String name;
    private int age;
    private String gender;

//    outsider has no access these data members , so we will use private but if we use
//    private diractly , then we have to use getters and setters(methods) ,
//    java has specialised  setters called constructors(its job is to set a data members)
//    How do we initialised?

//    we are taking only 3 data members because id is not given by the patient , it is generated by its own

    public Patient(String name ,int age, String gender){
        this.id =idCounter++;
            this.name=name;
            this.gender=gender;
            this.age=age;

    }



    public  int getId()
    {
        return id;
    }

    @Override
    public  String toString(){
        return "Patient Id :"+id + ",Name: " +name + ", gender :" + gender +", Age :" + age;
    }

}
